name: Deploy to Vercel

on:
  workflow_call:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: string
        default: 'preview'
    secrets:
      VERCEL_TOKEN:
        description: 'Vercel deployment token'
        required: true
      VERCEL_ORG_ID:
        description: 'Vercel organization ID'
        required: true
      VERCEL_PROJECT_ID:
        description: 'Vercel project ID'
        required: true

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ inputs.environment }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Output deployment URL
        run: |
          echo "🚀 Deployment completed!"
          echo "Environment: ${{ inputs.environment }}"
          echo "Check Vercel dashboard for deployment URL"
